---
title: "CovEd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(googlesheets4)
library(stringr)
```

```{r}
students <- read_sheet("https://docs.google.com/spreadsheets/d/1d8ZQT5LRv-LP5xyJn7NpSh-yRTvDNPe_C5u8ILUC0Ek/edit#gid=1099664139") %>% 
  clean_names() %>% 
  rename("subjects" = "which_subjects_would_you_like_to_receive_the_most_support_with_1st_choice")
```

```{r}
tutors <- read_sheet("https://docs.google.com/spreadsheets/d/1WF7al7SOlf3ntEUwVEa2BwQw10jfzwdfOO7lkM6QUvw/edit#gid=766034063") %>% 
  clean_names() %>% 
  rename("grade" = "what_grade_levels_are_you_comfortable_tutoring_mentoring",
         "subject" = "which_subjects_are_you_comfortable_helping_students_with")
```

```{r}
my_students <- students[c(551:570), ]

my_students %>% 
  group_by(grade_level) %>% 
  count()

```

```{r}
student_name_location_grade <- my_students %>% 
  select(student_name_first_and_last, grade_level, state, subjects) %>% 
  rename(student_name = student_name_first_and_last)

tutor_name_location_grade_subject <- tutors %>% 
  select(name, state, grade, subject) 

```

```{r}
current <- student_name_location_grade %>% 
  filter(grade_level == "11th") 

current
```

```{r}
tutor_name_location_grade_subject %>% 
  filter(str_detect(subject, "Computer Science")) 
```

```{r}
current_tutor <- tutor_name_location_grade_subject %>% 
  filter(str_detect(state, "CA")) %>% 
  filter(str_detect(subject, "AP U.S. History")) 
```

```{r}
  
my_freshmen <- student_name_location_grade %>% 
  filter(grade_level == "9th") 

my_sophomores <- student_name_location_grade %>% 
  filter(grade_level == "10th") 

my_juniors <- student_name_location_grade %>% 
  filter(grade_level == "11th")

my_seniors <- student_name_location_grade %>% 
  filter(grade_level == "12th") 
```

## Coercing AER resource

```{r}
aer <- read_sheet("https://docs.google.com/spreadsheets/d/18TiOCU3Ly3KcdrocCRLHwNTiaNqDoOcnva91f46Ee80/edit#gid=0") %>% 
  select(-7) %>% 
  clean_names()
```

```{r ajh}
aer <- aer %>% mutate(
  grade_age_group = sapply(grade_age_group, paste0, collapse="")) %>% 
  mutate(
  elementary = str_detect(grade_age_group,"K|1st|2nd|3rd|4th|5th"),
  middle = str_detect(grade_age_group,c("6th|7th|8th")),
  high = str_detect(grade_age_group,c("9th|10th|11th|12th|High School")) 
  )
  
aer <- aer %>% mutate(
  grade_age_group = sapply(grade_age_group, paste0, collapse="")) %>% 
  mutate(
  elementary = ifelse(str_detect(grade_age_group,"K|1st|2nd|3rd|4th|5th") == TRUE, "elementary", ""),
  middle = ifelse(str_detect(grade_age_group,c("6th|7th|8th"))==TRUE, "middle", ""),
  high = ifelse(str_detect(grade_age_group,c("9th|10th|11th|12th|High School")), "high school", ""),
  for_grade = paste(elementary, middle, high, sep = ", ") 
  ) 
```

```{r}

designations <- aer %>% 
  mutate(for_grade = 
          str_replace(for_grade, ", ,", "all ages")) 

designations1 <- designations %>% 
  mutate(for_grade = 
           str_replace(for_grade, "elementary, middle, high school", "K-12"))

designations2 <- designations1 %>% 
  mutate(for_grade =
           str_replace(for_grade, ", middle, high school", "Middle & High School (Grades 6-12)")) 

designations3 <- designations2 %>% 
  mutate(for_grade =
           str_replace(for_grade, "elementary, middle,", "Elementary & Middle School (Grades K-8)")) 

designations4 <- designations3 %>% 
  mutate(for_grade =
           str_replace(for_grade, "elementaryall ages", "Elementary School (KG-5th Grade)")) 

designations5 <- designations4 %>% 
  mutate(for_grade =
           str_replace(for_grade, ", middle,", "Middle School (6th-8th Grade)")) 

designations6 <- designations5 %>% 
  mutate(for_grade =
           str_replace(for_grade, "all ages high school", "High School (9th-12th Grade)"))

designations7 <- designations6 %>% 
  filter(!for_grade == "Elementary School (KG-5th Grade) high school")
```

```{r}
designations7[c("company", "for_grade", "category_subject", "link", "description")] %>%
  rename("This resource addresses the following subjects" = category_subject,
         "Resource Link" = link,
         "Resource Description" = description,
         "This resource is appropriate for students in" = for_grade)

```


Seniors: DONE
Juniors:
Sophomores:
Freshmen:
8th grade: NONE
7th grade: DONE
6th grade: NONE
5th grade: DONE
4th grade: DONE
3rd grade: DONE
2nd grade: DONE
1st grade: DONE
